language: node_js
node_js:
  - "node"
install: echo "Dependencies installed on Now"
script: echo "No build required"
deploy:
  provider: script
  script: npx now -t $TOKEN && npx now alias -t $TOKEN
  on:
    branch: master
