language: node_js
node_js:
  - "node"
install: echo "Dependencies installed on Now"
script: echo "No built required"
before_deploy: npm install now --no-save
deploy:
  provider: script
  script: now -t $TOKEN && now alias -t $TOKEN
  skip_cleanup: true
  on:
    branch: master
